version: '3.4'

services:
  fe-project:
    image: fe-project
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app/:rw
    ports:
      - 3000:3000
